openapi: 3.0.0
info:
  version: '1.0'
  title: REST API
  contact:
    name: Ivan
    email: i.am.ivan.ilinov@gmail.com
servers:
  - url: 'https://example.com/v1.0'
    description: Live Server
tags:
  - name: Раздел
    description: |
      API for Educational System
security:
  - SecretApiKey: []
  - JWT: []
paths:
  /createuser:
    post:
      summary: "Регистрация пользователя"
      description: 'Регистрирует пользователя в системе'
      tags: ['Register']
      security: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "i.i@gmail.com"
                password:
                  type: string
                  example: "1p2aSs_Wo4d"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      name:
                        type: string
                        example: "Ivan Ilinov"
                      email:
                        type: string
                        example: "o.o@gmail.com"
        '422':
          description: "Ошибка регистрации"
          content:
            application/json:
              schema:
                properties:
                  errors:
                    type: object
                    properties:
                      email:
                        type: array
                        items:
                          type: string
                          example: "Не указан Email"
                      password:
                        type: array
                        items:
                          type: string
                          example: "Не указан пароль"

  /auth:
    post:
      summary: "JWT токен"
      description: 'Выдаёт токен пользователю для осуществления операций'
      tags: ['Auth']
      security: []
      requestBody:
        #can be ref
        content:
          application/json:
            schema:
              #can be ref
              properties:
                email:
                  type: string
                  example: "i.i@gmail.com"
                password:
                  type: string
                  example: "1p2aSs_Wo4D"
        description: User object
        required: true
      responses:
        "200":
          description: OK
          content:
            applications/json:
              schema:
                properties:
                  user:
                    type: object
                      properties:
                        id:
                          type: string
                          example: 41
                        name:
                          type: string
                          example: "Ivan Ilinov"
                        email:
                          type: string
                          example: "i.i@gmail.com"
        '422':
          description: "Ошибка авторизации"
          content:
            application/json:
              schema:
                properties:
                  errors:
                    type: object
                    properties:
                      email:
                        type: array
                        items:
                          type: string
                          example: "Не указан Email"
                      password:
                        type: array
                        items:
                          type: string
                          example: "Не указан пароль"
  /students:
    get:
      summary: "Get list of Students"
      description: "Request for getting all students"
      tags:
        - Student
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                    name:
                      type: string
                  required:
                    - id
                    - name
        '404':
          description: Resource was not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    minimum: 100
                    maximum: 600
                    description: The HTTP status code.
                  error:
                    type: string
                  type:
                    type: string
                    description: >-
                      A URI reference [[RFC3986](https://tools.ietf.org/html/rfc3986)] that
                      identifies the problem type. It should provide human-readable
                      documentation for the problem type. When this member is not present, its
                      value is assumed to be "about:blank".
                  title:
                    type: string
                    description: >-
                      A short, human-readable summary of the problem type. It SHOULD NOT change
                      from occurrence to occurrence of the problem, except for purposes of
                      localization.
    post:
      summury: "Create entity Student"
      description: ""
      tags:
        - Student
      requestBody:
        content:
          application/json:
            schema:
              type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  name:
                    type: string
                required:
                  - id
                  - name
        description: Student object
        required: true
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    minimum: 0
                    description: The resource ID
                    example: 15
        '422':
          description: Invalid data was sent
          content:
            application/json:
              schema:
                description: Invalid data was sent
                allOf:
                  - type: object
                    properties:
                      status:
                        type: integer
                        minimum: 100
                        maximum: 600
                        description: The HTTP status code.
                      error:
                        type: string
                      type:
                        type: string
                        description: >-
                          A URI reference [[RFC3986](https://tools.ietf.org/html/rfc3986)] that
                          identifies the problem type. It should provide human-readable
                          documentation for the problem type. When this member is not present, its
                          value is assumed to be "about:blank".
                      title:
                        type: string
                        description: >-
                          A short, human-readable summary of the problem type. It SHOULD NOT change
                          from occurrence to occurrence of the problem, except for purposes of
                          localization.
                  - type: object
                    properties:
                      invalidFields:
                        type: array
                        items:
                          type: object
                          properties:
                            field:
                              type: string
                              description: >-
                                The field name. Dot notation is used for nested object field
                                names.
                            message:
                              type: string
                        example:
                          - field: field1
                            message: field1 is invalid
                          - field: subObject.field2
                            message: field2 is invalid
                          - field: subObject.field2
                            message: another error in the field2
  /student/{studentId}:
    get:
      summary: "Get Student by Id"
      description: "Request for getting student by Id"
      tags:
        - Student
      parameters:
        - name: studentId
          in: path
          description: >-
            Student identifier
          schema:
            type: integer
            minimum: 0
            description: The resource ID
            example: 15
          required: true
      responses:
        '200':
          description: Successful operation
            content:
              application/json:
                schema:
                  type: object
                    properties:
                      id:
                        type: integer
                        format: int64
                      name:
                        type: string
                    required:
                      - id
                      - name
        '404':
          description: Resource was not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    minimum: 100
                    maximum: 600
                    description: The HTTP status code.
                  error:
                    type: string
                  type:
                    type: string
                    description: >-
                      A URI reference [[RFC3986](https://tools.ietf.org/html/rfc3986)] that
                      identifies the problem type. It should provide human-readable
                      documentation for the problem type. When this member is not present, its
                      value is assumed to be "about:blank".
                  title:
                    type: string
                    description: >-
                      A short, human-readable summary of the problem type. It SHOULD NOT change
                      from occurrence to occurrence of the problem, except for purposes of
                      localization.

    patch:
      summary: "Update Student entity"
      description: "Request for update information about a Student entity"
      operationId: "updateStudent"
      tags:
        - Student
      parameters:
        - name: studentId
          in: path
          description: >-
            Student identifier
          schema:
            type: integer
            minimum: 0
            description: The resource ID
            example: 15
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                name:
                  type: string
              required:
                - id
                - name
        description: Student object
        required: true
      responses:
        '200':
          description: Student was updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  name:
                    type: string
                required:
                  - id
                  - name
        '422':
          description: Invalid data was sent
          content:
            application/json:
              schema:
                description: Invalid data was sent
                allOf:
                  - type: object
                    properties:
                      status:
                        type: integer
                        minimum: 100
                        maximum: 600
                        description: The HTTP status code.
                      error:
                        type: string
                      type:
                        type: string
                        description: >-
                          A URI reference [[RFC3986](https://tools.ietf.org/html/rfc3986)] that
                          identifies the problem type. It should provide human-readable
                          documentation for the problem type. When this member is not present, its
                          value is assumed to be "about:blank".
                      title:
                        type: string
                        description: >-
                          A short, human-readable summary of the problem type. It SHOULD NOT change
                          from occurrence to occurrence of the problem, except for purposes of
                          localization.
                  - type: object
                    properties:
                      invalidFields:
                        type: array
                        items:
                          type: object
                          properties:
                            field:
                              type: string
                              description: >-
                                The field name. Dot notation is used for nested object field
                                names.
                            message:
                              type: string
                        example:
                          - field: field1
                            message: field1 is invalid
                          - field: subObject.field2
                            message: field2 is invalid
                          - field: subObject.field2
                            message: another error in the field2

    delete:
      summary: "Delete Student"
      description: "Request for delete information about a Student"
      operationId: "deleteStudent"
      tags:
        - Student
      parameters:
        - name: studentId
          in: path
          description: >-
            Student identifier
          schema:
            type: integer
            minimum: 0
            description: The resource ID
            example: 15
          required: true
      responses:
        '200':
          description: Student was deleted
        '422':
          description: Invalid data was sent
          content:
            application/json:
              schema:
                description: Invalid data was sent
                allOf:
                  - type: object
                    properties:
                      status:
                        type: integer
                        minimum: 100
                        maximum: 600
                        description: The HTTP status code.
                      error:
                        type: string
                      type:
                        type: string
                        description: >-
                          A URI reference [[RFC3986](https://tools.ietf.org/html/rfc3986)] that
                          identifies the problem type. It should provide human-readable
                          documentation for the problem type. When this member is not present, its
                          value is assumed to be "about:blank".
                      title:
                        type: string
                        description: >-
                          A short, human-readable summary of the problem type. It SHOULD NOT change
                          from occurrence to occurrence of the problem, except for purposes of
                          localization.
                  - type: object
                    properties:
                      invalidFields:
                        type: array
                        items:
                          type: object
                          properties:
                            field:
                              type: string
                              description: >-
                                The field name. Dot notation is used for nested object field
                                names.
                            message:
                              type: string
                        example:
                          - field: field1
                            message: field1 is invalid
                          - field: subObject.field2
                            message: field2 is invalid
                          - field: subObject.field2
                            message: another error in the field2
  /subjects:
    get:
      summary: "Get list of Subjects"
      description: "Request for getting all subjects"
      tags:
        - Subject
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                    name:
                      type: string
                  required:
                    - id
                    - name
        '404':
          description: Resource was not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    minimum: 100
                    maximum: 600
                    description: The HTTP status code.
                  error:
                    type: string
                  type:
                    type: string
                    description: >-
                      A URI reference [[RFC3986](https://tools.ietf.org/html/rfc3986)] that
                      identifies the problem type. It should provide human-readable
                      documentation for the problem type. When this member is not present, its
                      value is assumed to be "about:blank".
                  title:
                    type: string
                    description: >-
                      A short, human-readable summary of the problem type. It SHOULD NOT change
                      from occurrence to occurrence of the problem, except for purposes of
                      localization.
    post:
      summury: "Create entity Subject"
      description: ""
      tags:
        - Subject
      requestBody:
        content:
          application/json:
            schema:
              type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  name:
                    type: string
                required:
                  - id
                  - name
        description: Subject object
        required: true
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    minimum: 0
                    description: The resource ID
                    example: 15
        '422':
          description: Invalid data was sent
          content:
            application/json:
              schema:
                description: Invalid data was sent
                allOf:
                  - type: object
                    properties:
                      status:
                        type: integer
                        minimum: 100
                        maximum: 600
                        description: The HTTP status code.
                      error:
                        type: string
                      type:
                        type: string
                        description: >-
                          A URI reference [[RFC3986](https://tools.ietf.org/html/rfc3986)] that
                          identifies the problem type. It should provide human-readable
                          documentation for the problem type. When this member is not present, its
                          value is assumed to be "about:blank".
                      title:
                        type: string
                        description: >-
                          A short, human-readable summary of the problem type. It SHOULD NOT change
                          from occurrence to occurrence of the problem, except for purposes of
                          localization.
                  - type: object
                    properties:
                      invalidFields:
                        type: array
                        items:
                          type: object
                          properties:
                            field:
                              type: string
                              description: >-
                                The field name. Dot notation is used for nested object field
                                names.
                            message:
                              type: string
                        example:
                          - field: field1
                            message: field1 is invalid
                          - field: subObject.field2
                            message: field2 is invalid
                          - field: subObject.field2
                            message: another error in the field2
  /subject/{subjectId}:
    get:
      summary: "Get Subject by Id"
      description: "Request for getting subject by Id"
      tags:
        - Subject
      parameters:
        - name: subjectId
          in: path
          description: >-
            Subject identifier
          schema:
            type: integer
            minimum: 0
            description: The resource ID
            example: 15
          required: true
      responses:
        '200':
          description: Successful operation
            content:
              application/json:
                schema:
                  type: object
                    properties:
                      id:
                        type: integer
                        format: int64
                      name:
                        type: string
                    required:
                      - id
                      - name
        '404':
          description: Resource was not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    minimum: 100
                    maximum: 600
                    description: The HTTP status code.
                  error:
                    type: string
                  type:
                    type: string
                    description: >-
                      A URI reference [[RFC3986](https://tools.ietf.org/html/rfc3986)] that
                      identifies the problem type. It should provide human-readable
                      documentation for the problem type. When this member is not present, its
                      value is assumed to be "about:blank".
                  title:
                    type: string
                    description: >-
                      A short, human-readable summary of the problem type. It SHOULD NOT change
                      from occurrence to occurrence of the problem, except for purposes of
                      localization.

    patch:
      summary: "Update Subject entity"
      description: "Request for update information about a Subject entity"
      operationId: "updateSubject"
      tags:
        - Subject
      parameters:
        - name: subjectId
          in: path
          description: >-
            Subject identifier
          schema:
            type: integer
            minimum: 0
            description: The resource ID
            example: 15
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                name:
                  type: string
              required:
                - id
                - name
        description: Subject object
        required: true
      responses:
        '200':
          description: Subject was updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  name:
                    type: string
                required:
                  - id
                  - name
        '422':
          description: Invalid data was sent
          content:
            application/json:
              schema:
                description: Invalid data was sent
                allOf:
                  - type: object
                    properties:
                      status:
                        type: integer
                        minimum: 100
                        maximum: 600
                        description: The HTTP status code.
                      error:
                        type: string
                      type:
                        type: string
                        description: >-
                          A URI reference [[RFC3986](https://tools.ietf.org/html/rfc3986)] that
                          identifies the problem type. It should provide human-readable
                          documentation for the problem type. When this member is not present, its
                          value is assumed to be "about:blank".
                      title:
                        type: string
                        description: >-
                          A short, human-readable summary of the problem type. It SHOULD NOT change
                          from occurrence to occurrence of the problem, except for purposes of
                          localization.
                  - type: object
                    properties:
                      invalidFields:
                        type: array
                        items:
                          type: object
                          properties:
                            field:
                              type: string
                              description: >-
                                The field name. Dot notation is used for nested object field
                                names.
                            message:
                              type: string
                        example:
                          - field: field1
                            message: field1 is invalid
                          - field: subObject.field2
                            message: field2 is invalid
                          - field: subObject.field2
                            message: another error in the field2

    delete:
      summary: "Delete Subject"
      description: "Request for delete information about a Subject"
      operationId: "deleteSubject"
      tags:
        - Subject
      parameters:
        - name: subjectId
          in: path
          description: >-
            Subject identifier
          schema:
            type: integer
            minimum: 0
            description: The resource ID
            example: 15
          required: true
      responses:
        '200':
          description: Subject was deleted
        '422':
          description: Invalid data was sent
          content:
            application/json:
              schema:
                description: Invalid data was sent
                allOf:
                  - type: object
                    properties:
                      status:
                        type: integer
                        minimum: 100
                        maximum: 600
                        description: The HTTP status code.
                      error:
                        type: string
                      type:
                        type: string
                        description: >-
                          A URI reference [[RFC3986](https://tools.ietf.org/html/rfc3986)] that
                          identifies the problem type. It should provide human-readable
                          documentation for the problem type. When this member is not present, its
                          value is assumed to be "about:blank".
                      title:
                        type: string
                        description: >-
                          A short, human-readable summary of the problem type. It SHOULD NOT change
                          from occurrence to occurrence of the problem, except for purposes of
                          localization.
                  - type: object
                    properties:
                      invalidFields:
                        type: array
                        items:
                          type: object
                          properties:
                            field:
                              type: string
                              description: >-
                                The field name. Dot notation is used for nested object field
                                names.
                            message:
                              type: string
                        example:
                          - field: field1
                            message: field1 is invalid
                          - field: subObject.field2
                            message: field2 is invalid
                          - field: subObject.field2
                            message: another error in the field2

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT